# Generated by Django 5.1.1 on 2024-11-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mente', '0003_bookmark_highlight_bookmark_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='tags',
        ),
    ]
